### ISSUE TITLE
Making files executable

### ISSUE THREAD

**Issue by skx** [BubblesToTheLimit/.emacs.d#1]
You have a section here:

* https://github.com/flyck/.emacs.d/blob/master/my-usepackages.org#make-bash-files-executable-on-save

That could _probably_ be reduced to:

```
(add-hook 'after-save-hook 'executable-make-buffer-file-executable-if-script-p)
```

That's what I do here:

* https://github.com/skx/dotfiles/blob/master/.emacs.d/init.md#unix-setup

**Comment by flyck** [comment]
Hey, doesn't work for me on my mac unfortunately with emacs 27.2

Seems like a good common config though: https://emacsredux.com/blog/2021/09/29/make-script-files-executable-automatically/

I might try this again in the future! 👍🏻 🙏🏻
